name: Python Control Structures Assignment

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test while loop
        run: python3 tests/test_assignment.py TestControlStructures.test_while_loop

      - name: Test for loop with continue
        run: python3 tests/test_assignment.py TestControlStructures.test_for_loop_continue

      - name: Test if-else statement
        run: python3 tests/test_assignment.py TestControlStructures.test_if_else